repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.12
    hooks:
      - id: ruff-check
      - id: ruff-format
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.351
    hooks:
      - id: pyright
        additional_dependencies:
          [beartype, jax, jaxtyping, pytest, typing_extensions]
