site_name: Statedict2Pytree

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
          selection:
            docstring_style: google

nav:
  - Home: index.md
  - API Reference:
      - Utils: utils.md
      - Statedict2Pytree: statedict2pytree.md
      - Examples: examples.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
