name: Run tests

on: [pull_request]

jobs:
  run-test:
    strategy:
      matrix:
        python-version: ["3.10"]
        os: [ubuntu-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install the project
        run: uv sync --locked --dev

      - name: Run pre-commit hooks
        run: |
          uv pip install pre-commit
          uv run pre-commit run --all-files

      - name: Run tests
        run: |
          uv run python -m pytest
